version: '3'

services:
  prismapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prismapp-container
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true